bootloader/usb_config.h, demo_composite_hid/usb_config.h, demo_gamepad/usb_config.h, rv003usb/rv003usb.S
bitstuff logic was inverted so any bit stuff was considered the end of a packet
fixes a lot of stuff, including device recognition on windows
also remove the pin order restriction
=> fix/clean up bit stuffing, use seqz, remove pin order restriction

bootloader/usb_config.h
~/rv003usb$ cd bootloader/
~/rv003usb/bootloader$ make clean build
rm -rf bootloader.elf bootloader.bin bootloader.hex bootloader.lst bootloader.map bootloader.hex || true
riscv64-unknown-elf-gcc -o bootloader.elf bootloader.c ../rv003usb/rv003usb.S -g -Os -flto -ffunction-sections -static-libgcc -march=rv32ec -mabi=ilp32e -I/usr/include/newlib -I../ch32v003fun/ch32v003fun/../extralibs -I../ch32v003fun/ch32v003fun -nostdlib -I. -Wall -I. -I../lib -DUSE_TINY_BOOT -I../rv003usb -T ch32v003fun-usb-bootloader.ld -Wl,--gc-sections -L../ch32v003fun/ch32v003fun/../misc -lgcc
../rv003usb/rv003usb.S: Assembler messages:
../rv003usb/rv003usb.S:54: Error: illegal operands `la a5,GPIO((GPIO_TypeDef*)(((0x40000000)+0x10000)+0x1400))_BASE'
../rv003usb/rv003usb.S:567: Error: illegal operands `la …
=> fix: bootloader fails to build

bootloader/Makefile, bootloader/bootloader.c, bootloader/make_win.bat, bootloader/usb_config.h
Adds windows support for the bootloader by fixing the USB and HID descriptors to proper values and adjusting end of scratchpad transfer detection.
Other than Linux, Windows will not allow any communication with a USB device that does not exactly follow the specs and matches USB descriptors.
The original USB descriptor advertises a `wMaxPacketSize` of 64 which is invalid for low speed USB devices, causing enumeration to fail on many host controllers. The maximum allowed for low speed devices is 8 Bytes.
The HID descriptor had a wrong Report Count and was missing a Report Size, resulting in an undefined or zero length of data it would accept.
Also added `make_win.bat` to build and flash the bootloader, as the make-file did not work properly for me on windows.
Fixes issues #21 and #24.
=> Windows support for bootloader

rv003usb/rv003usb.S
0x44 is the BDTR register, which incidentally contains the output enable bit (and breaks PWM output). 0x58 at least doesn't contain anything according to the data sheet and doesn't break anything for me
=> Change "go nowhere" location for debug timer when disabled

demo_composite_hid/usb_config.h
USB protocol errors occur in the composite HID demo due to an invalid min/max report descriptor for the mouse.  Fix this as intended for a three button mouse.
=> Fix the mouse composite HID report descriptor.

bootloader/bootloader.c, bootloader/usb_config.h
While the Pins already were configurable, the bootloader was still hardcoded to `PORTD`. This will fix it.
Also commented the commonly used Pinout.
=> make bootloader PORT configurable

bootloader/bootloader.c, bootloader/usb_config.h
This adds the option to configure a Button you have to press during boot to enter the Bootloader instead of (or in addition to) using Timeouts.
The Pin can be configured freely and even be on a different Port than the USB. It can be set to be a floating input, or pulled up or down. The level that triggers the bootloader can also be configured.
~~~c
// Bootloader Button Config
// If you want to use a Button during boot to enter bootloader, use these defines 
// to setup the Button. If you do, it makes sense to also set DISABLE_BOOTLOAD above, 
// set BOOTLOADER_TIMEOUT_PWR to 0 and disable BOOTLOADER_TIMEOUT_USB
#define BOOTLOADER_BTN_PORT D
#define BOOTLOADER_BTN_PIN 2
#define BOOTLOADER_BTN_TRIG_LEVEL 0 // 1 = HIGH; 0 = LOW
#define BOOTLOADER_BTN_PULL 1 // 1 = Pull-Up; 0 = Pull-Down; …
=> WIP: Add configurable Boot-Button

bootloader/bootloader.c, bootloader/usb_config.h
Adds two new #defines to configure the bootloader timeout
```c
// Timeout for bootloader after power-up, set to 0 to stay in bootloader forever
// 75ms per unit; 67 ~= 5s
#define BOOTLOADER_TIMEOUT_PWR 67
// Timeout (reset) for bootloader once USB Host is detected, set to 0 to stay in bootloader forever
// 75ms per unit; 0 costs 28 Bytes, >0 costs 48 Bytes; Comment out if not used
#define BOOTLOADER_TIMEOUT_USB 0
```
If set to e.g. 4 and 0 this will cause the bootloader to boot usercode after only 300ms if no USB Host is present. If an USB Host is present on power up, it will stay in bootloader forever. Perfectly for devices that only need USB for firmware updates but are otherwise just powered by battery / USB wallplug.
Also added a flag to configure if the Port used for USB is reset to …
=> Bootloader timeout configuration with Host detection

demo_composite_hid/demo_composite_hid.c, demo_composite_hid/usb_config.h, demo_gamepad/demo_gamepad.c, demo_hidapi/demo_hidapi.c
The composite_hid descriptor didn't work properly on Windows (Keyboard worked, but Mouse didn't). With this change it works on Windows, Linux and MacOS.  
Also added a delay between `SystemInit()` and `usb_setup()` to ensure re-enumeration after bootloader or reset. This works because the `D-` Pull-Up is disabled in that period. With a hardwired pullup one would need `D-` to be pulled low actively to achieve the same.
=> fix composite_hid descriptor and add re-enumeration delay

bootloader/bootloader.c, bootloader/usb_config.h, demo_composite_hid/usb_config.h, demo_gamepad/usb_config.h, demo_hidapi/usb_config.h, rv003usb/rv003usb.c
made USB_DPU optional. Just comment out `USB_DPU` if not needed / tied to 3V3 via 1.5K
=> made USB_DPU optional

README.md, bootloader/bootloader.c, bootloader/usb_config.h, demo_composite_hid/usb_config.h, demo_gamepad/usb_config.h, demo_hidapi/usb_config.h, rv003usb/rv003usb.S, rv003usb/rv003usb.c, rv003usb/rv003usb.h, testing/cdc_exp/usb_config.h, testing/demo_midi/usb_config.h, testing/demo_touchpad/README.md, testing/demo_touchpad/usb_config.h, testing/sandbox/usb_config.h, testing/test_ethernet/usb_config.h
Before this, USB_DP was used for D- and USB_DM was used for D+ due to historical reasons during development of the USB stack. This however is frustratingly confusing, so this should fix it.
This renames `USB_DM` to `USB_PIN_DP`, `USB_DP` to `USB_PIN_DM` and `USB_DPU` to `USB_PIN_DPU` (for consistency).
The changes include a fallback so previous code will still compile fine but issue a warning.
Users with
~~~c
#define USB_DM 3 // USB_DM is the physical USB D+ Pin!
#define USB_DP 4 // USB_DP is the physical USB D- Pin!
#define USB_DPU 5 // USB_DPU feeds the 1.5K Pull-Up on USB D- Pin! Comment out if not used / tied to 3V3!
#define USB_PORT D // Pins on PORT A, C or D
~~~
are encouraged to switch to
~~~c
#define USB_PIN_DP 3 // USB_PIN_DP is the physical USB D+ Pin!
#define USB_PIN_DM 4 // …
=> Rename USB_DM/USB_DP to end confusion

rv003usb/rv003usb.h
Throw an error if FUNCONF_SYSTICK_USE_HCLK is not set. FUNCONF_SYSTICK_USE_HCLK is required for USB to work.
Fixes #36
=> error if FUNCONF_SYSTICK_USE_HCLK is not set

bootloader/bootloader.c, bootloader/usb_config.h
This PR makes the port for the DPU pin configurable. For example, I'm using PA for USB DP/DN and PD for DPU. I tried to keep it backwards compatible so no changes are needed in usb_config.h unless the DPU port needs to be changed.
=> make port configurable for DPU pin

bootloader/bootloader.c
This helps to fit compiled binary in 1920 bytes if using button. Before it was 8 bytes over if you defined a button.
=> Fix bootloader.c for use with button

bootloader/bootloader.c
Issue:
```
Found B003Fun Bootloader
Halting Boot Countdown
Interface Setup
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol error
Warning: Issue with hid_send_feature_report. Retrying
ioctl (SFEATURE): Protocol …
```
=> Fix Bootloader not Flashing

demo_exti/Makefile, demo_exti/README.md, demo_exti/demo_exti.c, demo_exti/funconfig.h, demo_exti/usb_config.h, rv003usb/rv003usb.S
All additions to ``rv003usb.S`` are fenced with ``#ifdef``s, so unless you decide to use more interrupts, USB code stays the same. This addition is useful, because you can avoid editing the source of rv003usb in your project, making it more portable.
=> Add abitlity to use free EXTI channels by user code

bootloader/bootloader.c, bootloader/ch32v003fun-usb-bootloader.ld, rv003usb/rv003usb.c, rvswdio_programmer/README.md
Boards that doesn't have a dedicated DPU pin, can't properly re-enumerate from ``b003`` to ``d003`` after rebooting from bootloader. To fix this we need to pull down D- pin for a short period of time. To make this hassle free to the end user, I implemented it in the bootloader code plus corresponding changes to minichlink. This requires extra space, but it fits.
If you are still using dedicated DPU pin, only changes will be the extra 4 bytes used by the updated linker script.
Also fixed added one missing line to the soft reboot into bootloader function. Without it bootloader was booting straight into user code.
The last commit ensures that resulted bin will always be ``1920`` bytes, so we always rewrite whole boot partition and no junk could be left in the end of it from previous …
=> Fixing enumeration when rebooting into the program from bootloader

bootloader/ch32v003fun-usb-bootloader.ld, bootloader/usb_config.h
- XOR is not usable by LD on some systems (macos) for some reason
- macos couldn't enumerate USB bootloader with subclass ``0xFF``
=> Fixes to bootloader

bootloader/bootloader.c, rvswdio_programmer/rvswdio_programmer.c
Added a warning to bootloader.c that triggers if both the button and timeout are enabled as the firmware won't build with a confusing linker error.
Also added some macros to rvswdio to allow the use of open drain or inverted logic for the power pin.
=> Quality of Life improvements

rvswdio_programmer/README.md, rvswdio_programmer/bitbang_rvswdio.h, rvswdio_programmer/ch5xx.c, rvswdio_programmer/ch5xx.h, rvswdio_programmer/rvswdio_programmer.c, rvswdio_programmer/usb_config.h
Here is lots of stuff. It barely fits on v003, but it does. I think I can add *capability* check to report to minichlink what functions is it compiled with, and then minichlink can use generic functions for those that are missing. This will be encoded in programmer version after dot. Although I'm not sure why you want free space on your programmer...
=> Improve the programmer. Add CH5xx support
